### ISSUE TITLE
Switching from boy to girl needs visual feedback

### ISSUE THREAD

**Issue by rgdonohue** [FergusDevelopmentLLC/names-map-node#2]
Currently, nothing seems to happen when the user clicks from boy to girl. The functionality is set when the user searches for a new name?

Perhaps switching from one to the other automatically searches for the current name (with the new gender)?

**Comment by FergusDevelopmentLLC** [comment]
The names in the autocomplete are refreshed on change of the Boy/Girl switch to match the selected gender. Instead of searching, maybe the feedback from the switch is that name search input goes to edit mode and the placeholder text says "Search for a girl name" or "Search for a boy name" according to the switch value.

**Comment by rgdonohue** [comment]
Yes, that could work.
